#!/usr/bin/env python

import sys

def rot13(s):
result = ""
for i in range(len(s)):
c = s[i]
if 'a' <= c <= 'z':
result += chr((ord(c) - ord('a') + 13) % 26 + ord('a'))
elif 'A' <= c <= 'Z':
result += chr((ord(c) - ord('A') + 13) % 26 + ord('A'))
else:
result += c
return result

s = sys.stdin.read()
print(rot13(s))
