#!/usr/bin/env bash
# transfers a file to a remote server

if [ "$#" -ne 4 ]; then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

file_path="$1"
server_ip="$2"
username="$3"
ssh_key_path="$4"

if [ ! -f "$file_path" ]; then
	echo "Error: The specified file does not exist."
	exit 1
fi

#lets dissable host key checking for scp

scp_options=(-o StrictHostKeyChecking=no -i "$ssh_key_path")

echo "Transferring file to $username@$server_ip:~/"

if scp "${scp_options[@]}" "$file_path" "$username@$server_ip:~/"; then
	echo "File transfer successful."
else
	echo "Error: File transfer failed."
fi
