#!/usr/bin/env bash
# print the 23 hrs 59 mins
hours=0
minutes=1

while [[ $hours -lt 13 ]]; do
	echo "Hour: $hours"
	while [[ $minutes -lt 60 ]]; do
		echo $minutes
		minutes=$((minutes + 1))
	done
	minutes=1
	hours=$((hours + 1))
done
