#!/usr/bin/env bash
# Sets up nginx user
if ! command -v sudo &> /dev/null; then
  apk add --no-cache sudo
fi

if ! id -u nginx &>/dev/null; then
  adduser -D -H -s /sbin/nologin nginx
fi

sed -i 's/user\s*nginx;/user nginx;/' /etc/nginx/nginx.conf

sed -i '/listen\s*80;/c\    listen 8080 default_server;/g' /etc/nginx/conf.d/default.conf
service nginx restart
