#!/usr/bin/env bash

mkdir -p ~/.ssh/config

echo -e "Host *\n  IdentityFile ~/.ssh/school\n  PasswordAuthentication no" > ~/.ssh/config
echo "SSH client configuration updated. You can now connect to servers without a password."
